### ISSUE TITLE
Is it intended that `NewDocumentCommand` and `newcommand` are used at the same time?

### ISSUE THREAD

**Issue by ice1000** [matchy233/chi-cv-template#1]
https://github.com/matchy233/chi-cv-template/blob/a8c4850cc148cbf7411629cf52290889b5c78497/chicv.cls#L187-L194

**Comment by ice1000** [comment]
Similarly for `RenewDocumentCommand` and `renewcommand`. Ref: https://tex.stackexchange.com/a/98157/145304

**Comment by matchy233** [comment]
I must admit that I was too lazy to redefine the old command created before I introduced `xparse` to the template.

Since you noticed this little bad practice, I'll fix it soon 🤣
